apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/ai
components:
#  - ../../../../apps/ai/models/qwen359b/component
#  - ../../../../apps/ai/models/qwen352bvlembedding/component
