apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/ai
  - ../../../../apps/ai/models/qwen3635b/base
  - ../../../../apps/ai/models/qwen352bvlembedding/base
patches:
  - path: patches/qwen3635b-litellm-config.yaml
  - path: patches/qwen352bvlembedding-litellm-config.yaml
  - path: patches/qwen352bvlembedding-anything-llm-config.yaml
