apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: ai
data:
  30-qwen352bvlembedding.yaml: |
    - model_name: qwen352bvlembedding
      litellm_params:
        model: openai/qwen352bvlembedding
        api_base: http://kubeai.ai.svc.cluster.local/openai/v1
        api_key: "none"
