apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: ai
data:
  20-qwen3635b.yaml: |
    - model_name: qwen3635b
      litellm_params:
        model: openai/qwen3635b
        api_base: http://kubeai.ai.svc.cluster.local/openai/v1
        api_key: "none"
