apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../magic-cluster/infrastructure-observability
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: alertmanager
      namespace: observability
    path: patches/alertmanager-ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: grafana
      namespace: observability
    path: patches/grafana-ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: prometheus
      namespace: observability
    path: patches/prometheus-ingress.yaml
