apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-infrastructure-basis.yaml
  - 05-envoy-gateway.yaml
  - 10-identity-pilot.yaml
  - 15-magicstick-operator.yaml
  - 30-apps.yaml
