apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage
  namespace: ai
  labels:
    app: qdrant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "${AI_APPLIANCE_QDRANT_STORAGE:=1Gi}"
