apiVersion: v1
kind: Secret
metadata:
  name: qdrant-auth-secret
  namespace: ai
  labels:
    app: qdrant
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: QDRANT_API_KEY
type: Opaque
data: {}
