apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anything-llm-storage
  namespace: ai
  labels:
    app: anything-llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "${AI_APPLIANCE_ANYTHING_LLM_STORAGE:=1Gi}"
