apiVersion: v1
kind: ConfigMap
metadata:
  name: magicstick-mps-config
  namespace: gpu-operator
data:
  config.yaml: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      mps:
        renameByDefault: false
        failRequestsGreaterThanOne: true
        resources:
          - name: nvidia.com/gpu
            replicas: 1
