apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: magicstick-mps-control-daemon
  namespace: gpu-operator
  labels:
    app: magicstick-mps-control-daemon
spec:
  selector:
    matchLabels:
      app: magicstick-mps-control-daemon
  template:
    metadata:
      labels:
        app: magicstick-mps-control-daemon
    spec:
      hostPID: true
      runtimeClassName: nvidia
      priorityClassName: system-node-critical
      nodeSelector:
        nvidia.com/gpu.deploy.device-plugin: "true"
        nvidia.com/mps.capable: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      initContainers:
        - name: toolkit-validation
          image: nvcr.io/nvidia/gpu-operator:v26.3.2
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
          args:
            - until [ -f /run/nvidia/validations/toolkit-ready ]; do echo waiting for nvidia container stack to be setup; sleep 5; done
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: run-nvidia
              mountPath: /run/nvidia
              mountPropagation: HostToContainer
        - name: mps-control-daemon-mounts
          image: nvcr.io/nvidia/k8s-device-plugin:v0.19.2
          imagePullPolicy: IfNotPresent
          command:
            - mps-control-daemon
            - mount-shm
          securityContext:
            privileged: true
          volumeMounts:
            - name: mps-root
              mountPath: /mps
              mountPropagation: Bidirectional
      containers:
        - name: mps-control-daemon
          image: nvcr.io/nvidia/k8s-device-plugin:v0.19.2
          imagePullPolicy: IfNotPresent
          command:
            - mps-control-daemon
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
            - name: CONFIG_FILE
              value: /config/config.yaml
            - name: MIG_STRATEGY
              value: none
            - name: NVIDIA_MIG_MONITOR_DEVICES
              value: all
          securityContext:
            privileged: true
          volumeMounts:
            - name: mps-shm
              mountPath: /dev/shm
            - name: mps-root
              mountPath: /mps
            - name: config
              mountPath: /config
      volumes:
        - name: run-nvidia
          hostPath:
            path: /run/nvidia
            type: Directory
        - name: mps-root
          hostPath:
            path: /run/nvidia/mps
            type: DirectoryOrCreate
        - name: mps-shm
          hostPath:
            path: /run/nvidia/mps/shm
        - name: config
          configMap:
            name: magicstick-mps-config
