apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: qwen3635b
  namespace: ai
spec:
  features:
    - TextGeneration
  url: hf://cyankiwi/Qwen3.6-35B-A3B-AWQ-4bit
  engine: VLLM
  resourceProfile: magicstick-nvidia-gpu:1
  minReplicas: 1
  maxReplicas: 1
  env:
    MAGICSTICK_VLLM_VRAM_LIMIT: "15Gi"
    MAGICSTICK_VLLM_ACTIVE_THREAD_PERCENTAGE: "50"
  args:
    - --tensor-parallel-size=1
    - --max-model-len=8192
    - --max-num-seqs=128
    - --reasoning-parser=qwen3
    - --enable-auto-tool-choice
    - --tool-call-parser=qwen3_coder
