apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql
  namespace: identity-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    secret-generator.v1.mittwald.de/autogenerate: POSTGRES_PASSWORD
    secret-generator.v1.mittwald.de/encoding: hex
type: Opaque
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-bootstrap-admin
  namespace: identity-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    secret-generator.v1.mittwald.de/autogenerate: KC_BOOTSTRAP_ADMIN_PASSWORD
    secret-generator.v1.mittwald.de/encoding: hex
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: bootstrap-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-local-admin
  namespace: identity-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
stringData:
  username: local-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: magicstick-human-gateway-client
  namespace: identity-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    secret-generator.v1.mittwald.de/autogenerate: client-secret
type: Opaque
stringData:
  client-id: magicstick-human-gateway-local
