import type {Page} from '@playwright/test';
import {canonical} from '../core/borrowed-sharing.ts';
import {requireProof as requireSafe} from '../core/errors.ts';
import {poll} from '../core/poll.ts';

/** One exact request generated by the actual form. No broad API passthrough,
 * redirect, replay or mutation retry, and no response bodies in public logs. */
export async function permittedUiAction<T>(page:Page,origin:string,path:string,method:string,body:unknown,
  guard:()=>Promise<void>,action:()=>Promise<void>):Promise<T> {
  requireSafe(path.startsWith('/api/') && !path.includes('?') && !path.includes('#'),'CONFIG');
  let used=false,result:T|undefined;
  const handler=async(route:import('@playwright/test').Route)=>{
    requireSafe(!used && route.request().method() === method &&
      canonical(route.request().postData() ? route.request().postDataJSON() : null) === canonical(body),'MUTATION');
    used=true;await guard();
    const response=await route.fetch({maxRedirects:0}),bytes=await response.body();
    requireSafe(response.status() >= 200 && response.status() < 300 && bytes.length < 2*1024*1024,'API');
    result=(bytes.length ? JSON.parse(bytes.toString()) : {}) as T;
    await route.fulfill({response});
  };
  await page.route(origin+path,handler);
  try {
    await action();await poll(async()=>result,value=>value !== undefined,{timeoutMs:30_000,intervalMs:100,stage:'model-update'});
    requireSafe(used && result !== undefined,'API');return result;
  }finally{await page.unroute(origin+path,handler);}
}
