apiVersion: appliance.magicstick.dev/v1alpha1
kind: Appliance
metadata:
  name: local
  namespace: ai-system
spec:
  profile: minimal
  source:
    kind: GitRepository
    name: magicstick-public
    namespace: flux-system
  modules:
    basis:
      enabled: true
    dashboard:
      enabled: true
