apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litellm-postgresql
  namespace: ai
  labels:
    app: litellm-postgresql
spec:
  serviceName: litellm-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: litellm-postgresql
  template:
    metadata:
      labels:
        app: litellm-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16.4
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: litellm-postgresql-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: litellm-postgresql-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: litellm-postgresql-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: litellm-postgresql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "${AI_APPLIANCE_LITELLM_POSTGRES_STORAGE:=1Gi}"
