apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeai
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: ai
  chart:
    spec:
      chart: kubeai
      version: "0.23.2"
      sourceRef:
        kind: HelmRepository
        name: kubeai
        namespace: flux-system
  install:
    createNamespace: false
  values:
    crds:
      enabled: true
    open-webui:
      enabled: false
    service:
      type: ClusterIP
    ingress:
      enabled: false
    modelServers:
      VLLM:
        images:
          magicstick-vllm: vllm/vllm-openai:v0.23.0
    resourceProfiles:
      magicstick-nvidia-gpu:
        imageName: magicstick-vllm
        requests:
          cpu: "6"
          memory: 6Gi
          nvidia.com/gpu: "1"
        limits:
          nvidia.com/gpu: "1"
        tolerations:
          - key: nvidia.com/gpu
            operator: Equal
            value: present
            effect: NoSchedule
    modelServerPods:
      jsonPatches:
        - op: replace
          path: /spec/volumes/0
          value:
            name: dshm
            hostPath:
              path: /run/nvidia/mps/shm
              type: DirectoryOrCreate
        - op: replace
          path: /spec/containers/0/command
          value:
            - python3
            - /opt/magicstick/vllm-wrapper/wrapper.py
        - op: add
          path: /spec/volumes/-
          value:
            name: model-cache
            hostPath:
              path: /root/.cache
              type: DirectoryOrCreate
        - op: add
          path: /spec/volumes/-
          value:
            name: magicstick-vllm-wrapper
            configMap:
              name: magicstick-vllm-wrapper
        - op: add
          path: /spec/volumes/-
          value:
            name: mps-root
            hostPath:
              path: /run/nvidia/mps
              type: DirectoryOrCreate
        - op: add
          path: /spec/containers/0/volumeMounts/-
          value:
            name: model-cache
            mountPath: /root/.cache
        - op: add
          path: /spec/containers/0/volumeMounts/-
          value:
            name: magicstick-vllm-wrapper
            mountPath: /opt/magicstick/vllm-wrapper
            readOnly: true
        - op: add
          path: /spec/containers/0/volumeMounts/-
          value:
            name: mps-root
            mountPath: /mps
