apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubeopencode
  namespace: flux-system
spec:
  type: oci
  interval: 1h0m0s
  url: oci://ghcr.io/kubeopencode/helm-charts
