apiVersion: v1
kind: Secret
metadata:
  name: litellm-masterkey-secret
  namespace: ai
  labels:
    app: litellm
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    secret-generator.v1.mittwald.de/autogenerate: LITELLM_MASTER_KEY
type: Opaque
data: {}
