apiVersion: v1
kind: Secret
metadata:
  name: litellm-postgresql-secret
  namespace: ai
  labels:
    app: litellm
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    secret-generator.v1.mittwald.de/autogenerate: POSTGRES_PASSWORD
    secret-generator.v1.mittwald.de/encoding: "hex"
type: Opaque
stringData:
  POSTGRES_DB: litellm
  POSTGRES_USER: litellm
