apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: qwen352bvlembedding
  namespace: ai
spec:
  features:
    - TextEmbedding
  url: hf://LifetimeMistake/Qwen3-VL-Embedding-2B-AWQ-4bit
  engine: VLLM
  resourceProfile: magicstick-nvidia-gpu:1
  minReplicas: 1
  maxReplicas: 1
  env:
    MAGICSTICK_VLLM_VRAM_LIMIT: "5Gi"
    MAGICSTICK_VLLM_ACTIVE_THREAD_PERCENTAGE: "100"
  args:
    - --runner=pooling
    - --convert=embed
    - --trust-remote-code
    - --quantization=compressed-tensors
    - --limit-mm-per-prompt
    - '{"image":1}'
    - --max-model-len=4096
