apiVersion: v1
kind: Service
metadata:
  name: qwen352bvlembedding
  namespace: ai
  labels:
    app: qwen352bvlembedding
spec:
  type: ClusterIP
  selector:
    app: qwen352bvlembedding
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
