apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: observability
  labels:
    app: grafana
  annotations:
    lab42.io/mdns.enabled: "true"
    lab42.io/mdns.name: "grafana"
    lab42.io/mdns.host: "grafana"
spec:
  ingressClassName: nginx
  rules:
    - host: "grafana.${AI_APPLIANCE_DOMAIN:=example.local}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: observability-kube-prometheus-stack-grafana
                port:
                  number: 80
    - host: grafana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: observability-kube-prometheus-stack-grafana
                port:
                  number: 80
