apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../infra-cluster/apps-ai
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: anything-llm
      namespace: ai
    path: patches/anything-llm-ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: litellm
      namespace: ai
    path: patches/litellm-ingress.yaml
