apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../ai
  - ../../../ai/models/qwen3635b/overlays/single-node
  - ../../../ai/models/qwen352bvlembedding/overlays/single-node
patches:
  - path: patches/qwen3635b-litellm-config.yaml
  - path: patches/qwen352bvlembedding-litellm-config.yaml
  - path: patches/qwen352bvlembedding-anything-llm-config.yaml
