apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../base
configMapGenerator:
  - name: litellm-config
    namespace: ai
    behavior: merge
    files:
      - 20-qwen3635b.yaml=litellm-fragment.yaml
generatorOptions:
  disableNameSuffixHash: true
