apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crds/appliances.appliance.magicstick.dev.yaml
  - rbac.yaml
  - module-catalog.yaml
  - deployment.yaml
  - default-appliance.yaml
