apiVersion: v1
kind: ServiceAccount
metadata:
  name: magicstick-operator
  namespace: ai-system
  labels:
    app.kubernetes.io/name: magicstick-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: magicstick-operator
  labels:
    app.kubernetes.io/name: magicstick-operator
rules:
  - apiGroups:
      - appliance.magicstick.dev
    resources:
      - appliances
      - appliances/status
      - appliances/finalizers
      - moduleactivations
      - moduleactivations/status
      - moduleactivations/finalizers
      - appinstances
      - appinstances/status
      - appinstances/finalizers
      - modelactivations
      - modelactivations/status
      - modelactivations/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - kubeai.org
    resources:
      - models
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - kustomize.toolkit.fluxcd.io
    resources:
      - kustomizations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - referencegrants
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - gateway.envoyproxy.io
    resources:
      - securitypolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - gitrepositories
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: magicstick-operator
  labels:
    app.kubernetes.io/name: magicstick-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: magicstick-operator
subjects:
  - kind: ServiceAccount
    name: magicstick-operator
    namespace: ai-system
