apiVersion: v1
kind: Secret
metadata:
  name: forgejo-admin-secret
  namespace: development
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
stringData:
  username: admin
  email: admin@example.com
