apiVersion: v1
kind: Secret
metadata:
  name: forgejo-postgresql-secret
  namespace: development
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: POSTGRES_PASSWORD
type: Opaque
data: {}
