apiVersion: v1
kind: Secret
metadata:
  name: forgejo-security-secret
  namespace: development
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: SECRET_KEY
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-internal-token-secret
  namespace: development
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: INTERNAL_TOKEN
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-lfs-jwt-secret
  namespace: development
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: LFS_JWT_SECRET
type: Opaque
data: {}
