# SPDX-License-Identifier: BUSL-1.1
"""Render the handbook's reviewed diagrams as deterministic, self-contained SVGs.

The drawing functions below are the editable sources. No browser, network,
third-party renderer, fonts or JavaScript is needed to generate or read them.
"""
import argparse
from html import escape
from pathlib import Path


OUTPUT = Path(__file__).resolve().parents[1] / 'docs/assets/diagrams'
COLORS = {
    'background': '#080f1b', 'surface': '#0e1b2b', 'border': '#29405a',
    'text': '#e6edf8', 'muted': '#b8c8db', 'cyan': '#35cfe6',
    'purple': '#a58bfa', 'green': '#55d8ae', 'amber': '#f5c95c',
}


class Diagram:
    """Small SVG vocabulary; all prose and layout stay explicit and reviewable."""

    def __init__(self, name, height, title, description, subtitle):
        self.name = name
        self.parts = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<!-- SPDX-License-Identifier: BUSL-1.1 -->',
            '<!-- Generated by tools/docs_diagrams.py. Edit that source, not this SVG. -->',
            f'<svg xmlns="http://www.w3.org/2000/svg" width="640" height="{height}" '
            f'viewBox="0 0 640 {height}" role="img" '
            f'aria-labelledby="{name}-title {name}-desc">',
            f'<title id="{name}-title">{escape(title)}</title>',
            f'<desc id="{name}-desc">{escape(description)}</desc>',
            '<defs>',
        ]
        for color in ('cyan', 'purple', 'muted', 'amber'):
            self.parts.append(
                f'<marker id="arrow-{color}" viewBox="0 0 10 10" refX="9" refY="5" '
                f'markerWidth="8" markerHeight="8" orient="auto-start-reverse">'
                f'<path d="M 1 1 L 9 5 L 1 9" fill="none" stroke="{COLORS[color]}" '
                'stroke-width="1.5" stroke-linejoin="round"/></marker>')
        self.parts += ['</defs>',
                       '<g font-family="system-ui, -apple-system, Segoe UI, Arial, sans-serif">']
        self.rect(0, 0, 640, height, 'background', radius=16, border=False)
        self.text(32, 52, title, size=30, weight=650)
        self.text(32, 88, subtitle, color='muted', size=22)

    def rect(self, x, y, width, height, fill='surface', radius=12,
             border=True, dashed=False, stroke='border'):
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{width}" height="{height}" rx="{radius}" '
            f'fill="{COLORS[fill]}" stroke="{COLORS[stroke] if border else "none"}" '
            f'stroke-width="1.5"' + (' stroke-dasharray="7 6"' if dashed else '') + '/>')

    def text(self, x, y, lines, size=22, color='text', weight=400, anchor='start', gap=30):
        if isinstance(lines, str):
            lines = [lines]
        self.parts.append(f'<text x="{x}" y="{y}" fill="{COLORS[color]}" '
                          f'font-size="{size}" font-weight="{weight}" text-anchor="{anchor}">')
        for index, line in enumerate(lines):
            self.parts.append(f'<tspan x="{x}" dy="{0 if index == 0 else gap}">{escape(line)}</tspan>')
        self.parts.append('</text>')

    def arrow(self, points, color='cyan', dashed=False):
        path = 'M ' + ' L '.join(f'{x} {y}' for x, y in points)
        self.parts.append(f'<path d="{path}" fill="none" stroke="{COLORS[color]}" '
                          'stroke-width="2" stroke-linejoin="round" '
                          f'marker-end="url(#arrow-{color})"' +
                          (' stroke-dasharray="7 6"' if dashed else '') + '/>')

    def result(self):
        return '\n'.join([*self.parts, '</g>', '</svg>', ''])


def architecture():
    d = Diagram('architecture', 1110, 'One platform, two paths',
                'Configuration: the dashboard saves ModelActivation settings; the Magic Stick '
                'Operator reconciles local runtimes through KubeAI for Ollama and ordinary vLLM, '
                'or direct workloads for FreeToken and Realtime vLLM-Omni. Inference: applications '
                'and API clients call LiteLLM, which routes to the local runtime. The model catalog '
                'publishes ready local routes. Each runtime uses its supported CPU or GPU target. '
                'Authentication, module provisioning and external-provider routes are omitted.',
                'Simplified local-model architecture')
    d.text(32, 142, 'CONFIGURATION', color='purple', weight=650)
    d.text(340, 142, 'INFERENCE', color='cyan', weight=650)
    for x in (32, 340):
        d.rect(x, 165, 268, 90)
        d.rect(x, 314, 268, 114)
    d.text(166, 219, 'Dashboard', size=26, weight=650, anchor='middle')
    d.text(474, 203, ['Applications', 'and API clients'], anchor='middle')
    d.text(166, 356, 'Saved settings', size=25, weight=650, anchor='middle')
    d.text(166, 395, 'ModelActivation', anchor='middle', color='muted')
    d.text(474, 358, 'LiteLLM', size=26, weight=650, anchor='middle')
    d.text(474, 396, 'API and routing', anchor='middle', color='muted')
    d.arrow([(166, 255), (166, 314)], color='purple', dashed=True)
    d.arrow([(474, 255), (474, 314)])
    d.rect(32, 487, 268, 110)
    d.text(166, 532, ['Magic Stick', 'Operator'], size=25, weight=650, anchor='middle')
    d.arrow([(166, 428), (166, 487)], color='purple', dashed=True)
    d.text(340, 503, ['The model catalog', 'publishes ready', 'local routes.'], color='muted')
    d.arrow([(166, 597), (166, 665)], color='purple', dashed=True)
    # Request traffic does not travel through the operator or the catalog.
    d.arrow([(608, 371), (624, 371), (624, 774), (608, 774)])
    d.rect(32, 665, 576, 203)
    d.text(56, 709, 'Local inference runtimes', size=26, weight=650)
    d.text(56, 758, ['Ollama / vLLM', 'KubeAI-managed'])
    d.text(342, 758, ['FreeToken /', 'Realtime (Omni)', 'Direct workloads'])
    d.arrow([(320, 868), (320, 930)])
    d.rect(32, 930, 576, 112)
    d.text(320, 974, 'CPU or supported GPU', size=26, weight=650, anchor='middle')
    d.text(320, 1010, 'Compatibility depends on the engine.', anchor='middle', color='muted')
    d.text(32, 1080, 'Dashed: configuration · Solid: inference', size=22, color='muted')
    return d.result()


def lifecycle():
    d = Diagram('model-lifecycle', 1330, 'From Start to Ready',
                'Create or Start saves and enables a local model. During startup the controller '
                'prepares dependencies and resources; the runtime downloads weights if needed, loads '
                'the model and checks health. A ready model can be published to LiteLLM. A failure '
                'can report Degraded: inspect Logs and resolve its cause. Stop removes the runtime '
                'and withdraws the route. During Removing, allocations are still terminating; '
                'Disabled retains the settings. Start reuses those settings. Remove deletes the '
                'definition; cache cleanup is a separate action. This is a simplified workflow, '
                'not an exhaustive state machine; exact startup labels vary by engine.',
                'Local models · simplified workflow')
    d.rect(32, 140, 352, 103)
    d.text(208, 181, 'Create / Start', size=26, weight=650, anchor='middle')
    d.text(208, 218, 'Enable saved settings', anchor='middle', color='muted')
    d.arrow([(208, 243), (208, 308)])
    d.rect(32, 308, 352, 211)
    d.text(56, 351, 'Startup', size=26, weight=650)
    d.text(56, 395, ['Prepare and schedule', 'Download if needed', 'Load model', 'Check health'])
    d.arrow([(384, 369), (428, 369)], color='amber')
    d.rect(428, 322, 180, 160)
    d.text(518, 359, 'Degraded', size=24, weight=650, color='amber', anchor='middle')
    d.text(518, 407, ['Open Logs', 'Fix cause'], anchor='middle')
    d.text(428, 529, ['Then retry /', 'reconcile.'], size=22, color='muted')
    d.arrow([(208, 519), (208, 580)])
    d.rect(32, 580, 352, 108)
    d.text(208, 624, 'Ready', size=26, color='green', weight=650, anchor='middle')
    d.text(208, 660, 'Published to LiteLLM', anchor='middle', color='muted')
    d.arrow([(208, 688), (208, 774)], color='muted')
    d.text(230, 740, 'Stop', weight=650)
    d.rect(32, 774, 352, 113)
    d.text(208, 815, 'Removing', size=26, weight=650, anchor='middle')
    d.text(208, 853, 'Wait for runtime cleanup', anchor='middle', color='muted')
    d.arrow([(208, 887), (208, 953)], color='muted')
    d.rect(32, 953, 352, 123)
    d.text(208, 995, 'Disabled', size=26, weight=650, anchor='middle')
    d.text(208, 1031, ['Settings kept', 'No active route'], anchor='middle', color='muted')
    d.arrow([(384, 1014), (624, 1014), (624, 191), (384, 191)], color='purple', dashed=True)
    d.text(437, 993, 'Start again', color='purple', weight=650)
    d.rect(32, 1125, 576, 170)
    d.text(56, 1166, 'Different actions, different effects', size=24, weight=650)
    d.text(56, 1207, ['Stop: keep the saved model definition.',
                      'Remove: delete the definition as well.',
                      'Clear cache: manage downloads separately.'])
    return d.result()


def memory():
    d = Diagram('memory-and-sharing', 1420, 'Memory is not model slots',
                'A discrete GPU has dedicated VRAM separate from system RAM. A unified-memory '
                'GPU such as Strix Halo uses physical RAM: a firmware GPU reservation is unavailable '
                'to Linux, and CPU plus dynamic GPU allocations compete for Linux-visible RAM. '
                'The dynamic GPU ceiling is a limit inside that RAM, not protected extra memory. '
                'Firmware and dynamic pools cannot be blindly summed for model fit. Free memory '
                'comes from live telemetry; unreserved budget subtracts planned reservations. '
                'GPU admission also needs a free model slot. The illustrative four slots show '
                'two used and two free, not four GPUs or four isolated VRAM partitions. '
                'Shared AMD uses DRA and shared NVIDIA uses time-slicing where supported.',
                'Physical pools, current usage and admission')
    d.text(32, 146, '1  Dedicated GPU memory', size=25, weight=650)
    d.rect(32, 171, 272, 139)
    d.rect(336, 171, 272, 139)
    d.text(168, 214, 'System RAM', size=24, weight=650, anchor='middle')
    d.text(168, 253, ['CPU + optional', 'engine offloading'], color='muted', anchor='middle')
    d.text(472, 214, 'Discrete GPU', size=24, weight=650, anchor='middle')
    d.text(472, 268, 'Dedicated VRAM', anchor='middle', color='cyan')
    d.text(320, 348, 'Separate physical memory pools', anchor='middle', color='muted')

    d.text(32, 409, '2  Unified memory · Strix Halo', size=25, weight=650)
    d.rect(32, 434, 576, 344)
    d.text(56, 475, 'One physical RAM pool', size=24, weight=650)
    d.rect(56, 503, 172, 202, fill='background')
    d.text(142, 541, ['Firmware', 'GPU reserve'], anchor='middle', color='cyan', weight=650)
    d.text(142, 634, ['Unavailable', 'to Linux'], anchor='middle', color='muted')
    d.rect(248, 503, 336, 202, fill='background')
    d.text(416, 541, 'Linux-visible RAM', size=24, weight=650, anchor='middle')
    d.text(416, 579, 'CPU + dynamic GPU use', anchor='middle')
    d.rect(267, 605, 298, 80, fill='surface', stroke='purple', dashed=True)
    d.text(416, 637, ['GPU ceiling: a limit,', 'not a reservation'], anchor='middle', color='purple', gap=29)
    d.text(56, 744, 'Not an additive model-fit guarantee.', color='muted')

    d.text(32, 842, '3  Two different memory readings', size=25, weight=650)
    d.rect(32, 866, 576, 135)
    d.text(56, 909, 'Free = live telemetry', color='cyan', weight=650)
    d.text(56, 954, ['Unreserved = budget after', 'planned model reservations'], color='purple')

    d.text(32, 1065, '4  Model slots are a separate limit', size=25, weight=650)
    d.text(32, 1105, 'Example: 2 used slots, 2 free slots', color='muted')
    for index, label in enumerate(('Used', 'Used', 'Free', 'Free')):
        x = 32 + index * 148
        d.rect(x, 1130, 132, 65, fill='border' if index < 2 else 'surface')
        d.text(x + 66, 1171, label, anchor='middle',
               color='muted' if index < 2 else 'green', weight=650)
    d.text(32, 1242, ['Admission needs memory AND a free slot.',
                      'Slots do not partition VRAM.'], weight=650)
    d.text(32, 1344, ['Shared mode, where supported:',
                      'AMD DRA / NVIDIA time-slicing'], color='muted')
    return d.result()


def render_all():
    return {
        'architecture.svg': architecture(),
        'model-lifecycle.svg': lifecycle(),
        'memory-and-sharing.svg': memory(),
    }


def check(directory=OUTPUT):
    errors = []
    for name, expected in render_all().items():
        path = directory / name
        if not path.is_file() or path.read_text(encoding='utf-8') != expected:
            errors.append(f'Diagram missing or stale: {name}; run python tools/docs_diagrams.py')
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check without rewriting files.')
    args = parser.parse_args()
    if args.check:
        errors = check()
        print('\n'.join(errors) if errors else 'All handbook diagrams match their sources.')
        return 1 if errors else 0
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for name, content in render_all().items():
        (OUTPUT / name).write_text(content, encoding='utf-8')
        print(f'Rendered {name}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
