# SPDX-License-Identifier: BUSL-1.1
"""Validate shared Markdown sources and build the complete static Pages artifact."""
import argparse
from concurrent.futures import ThreadPoolExecutor
import html
from html.parser import HTMLParser
import ipaddress
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from urllib.parse import unquote, urlsplit
from urllib.request import Request, urlopen

import markdown
import yaml

if __package__:
    from . import docs_diagrams
else:
    import docs_diagrams

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / 'docs'
OUT = ROOT / 'dist/docs-site'
CATALOG = ROOT / 'magic-cluster/platform/magicstick-operator/compute-target-catalog.yaml'
REPO = 'https://github.com/QualityMinds/AIppliance-Magic-Stick'
MARKETING_PAGES = ('index.html', 'de.html', 'editions.html', 'editionen.html',
                   'legal-notice.html', 'privacy.html')


class Links(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []
        self.ids = set()

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        for key in ('id', 'name'):
            if attrs.get(key): self.ids.add(attrs[key])
        if tag == 'a' and attrs.get('href'): self.links.append(attrs['href'])
        if tag in ('img', 'script', 'iframe', 'source') and attrs.get('src'):
            self.links.append(attrs['src'])
        if tag == 'link' and attrs.get('href') and attrs.get('rel') != 'canonical':
            self.links.append(attrs['href'])


def github_headings(text):
    counts, result, fence = {}, set(), None
    for line in text.splitlines():
        f = re.match(r'^\s*(`{3,}|~{3,})', line)
        if f:
            if fence is None: fence = f[1][0]
            elif fence == f[1][0]: fence = None
            continue
        if fence: continue
        match = re.match(r'^#{1,6}\s+(.+?)\s*#*\s*$', line)
        if not match: continue
        label = re.sub(r'<[^>]+>', '', match[1]).lower()
        slug = re.sub(r'[^\w\- ]', '', label).replace(' ', '-')
        n = counts.get(slug, 0)
        counts[slug] = n + 1
        result.add(slug + (f'-{n}' if n else ''))
    return result


def parse(path):
    text = path.read_text(encoding='utf-8')
    parser = Links()
    parser.feed(markdown.markdown(text, extensions=['fenced_code', 'tables']) if path.suffix == '.md' else text)
    if path.suffix == '.md': parser.ids.update(github_headings(text))
    return parser


def local_target(source, href, root, public_prefix=''):
    url = urlsplit(href)
    if url.scheme or url.netloc: return None
    path = unquote(url.path)
    if public_prefix and (path == public_prefix or path.startswith(public_prefix + '/')):
        path = path[len(public_prefix):] or '/'
    target = (root / path.lstrip('/') if path.startswith('/') else source.parent / path) if path else source
    target = Path(os.path.normpath(target))
    if target.is_dir():
        for name in ('index.html', 'README.md', 'index.md'):
            if (target / name).is_file():
                target = target / name
                break
    return target, unquote(url.fragment)


def check_links(paths, root, public_prefix=''):
    errors, cache = [], {}
    def cached(path):
        if path not in cache: cache[path] = parse(path)
        return cache[path]
    for source in paths:
        data = cached(source)
        for href in data.links:
            resolved = local_target(source, href, root, public_prefix)
            if not resolved: continue
            target, fragment = resolved
            if not target.exists():
                errors.append(f'{source.relative_to(root)}: missing target {href}')
            elif fragment and target.suffix in ('.md', '.html'):
                ids = cached(target).ids
                if fragment not in ids:
                    errors.append(f'{source.relative_to(root)}: missing anchor {href}')
    return sorted(set(errors))


def source_files():
    names = subprocess.check_output(['git', 'ls-files', '--cached', '--others', '--exclude-standard', '-z'], cwd=ROOT).decode().split('\0')
    return sorted({ROOT / n for n in names if n and not n.startswith('.codex/')
                   and (ROOT / n).is_file() and (Path(n).suffix == '.md'
                   or (Path(n).suffix == '.html' and n.startswith('docs/')))})


def compatibility():
    manifest = yaml.safe_load(CATALOG.read_text())
    data = json.loads(manifest['data']['targets.json'])
    engines = data['engines']
    rows = ['# Engine and hardware compatibility', '',
            '<!-- Generated by tools/docs.py inventory. Edit the catalog, not this table. -->', '',
            'This page describes the repository capability catalog, not successful tests on every device.',
            'Availability also requires live driver/resource readiness, free slots and usable memory telemetry.', '',
            'Source: [compute-target catalog](../../magic-cluster/platform/magicstick-operator/compute-target-catalog.yaml).', '',
            '## Ordinary engine targets', '',
            '| Compute target | Architecture | Configured engines |', '|---|---|---|']
    for target in data['targets'].values():
        rows.append('| ' + target['displayName'] + ' | ' + ', '.join(target['architectures']) + ' | ' +
                    ', '.join(engines[e]['displayName'] for e in target.get('engines', [])) + ' |')
    cap = engines['FreeToken']['capabilities']
    rows += ['', '## FreeToken admission policy', '',
             f"- Upstream version: `{cap['version']}`.",
             f"- OS / host architecture: {', '.join(cap['operatingSystems'])} / {', '.join(cap['supportedArchitectures'])}.",
             f"- Vendor: {', '.join(cap['supportedVendors'])}; NVIDIA driver major at least {cap['minimumNvidiaDriverMajor']}; CUDA major {cap['requiredCudaMajor']}.",
             f"- Admitted compute capabilities: {', '.join(cap['supportedComputeCapabilities'])}.",
             f"- Allocation contract: `{cap['deviceBinding']}`; whole homogeneous GPUs, not MIG or time-slicing slots.",
             f"- Memory strategies: {', '.join(cap['memoryStrategies'])}; start with `auto`.",
             f"- Precision choices: {', '.join(cap['supportedPrecisionModes'])}.",
             '- Model IDs are checked against the catalog policy; a family name is not blanket approval.', '',
             'See [FreeToken configuration](freetoken.md) and the [user guide](../user-guide/models/freetoken.md).', '',
             '## Experimental Realtime profiles', '',
             'These are runtime selections, not hardware or model certifications. An empty image needs an explicitly compatible runtime.', '',
             '| Profile | Compute target | Requested device counts | Bundled image |', '|---|---|---|---|']
    for key, profile in engines['VLLM'].get('realtimeProfiles', {}).items():
        rows.append(f"| `{key}` | {', '.join(profile['computeTargets'])} | {', '.join(map(str, profile['gpuCounts']))} | {'Pinned' if profile.get('image') else 'Not supplied'} |")
    rows += ['', 'A CPU profile has no physical GPU despite its stage/device-count convention.',
             'See [Realtime](../user-guide/models/realtime.md) and [GPU operator support](gpu-operators.md) for additional boundaries.', '']
    return '\n'.join(rows)


def nav_paths(value):
    if isinstance(value, str): yield value
    elif isinstance(value, list):
        for item in value: yield from nav_paths(item)
    elif isinstance(value, dict):
        for item in value.values(): yield from nav_paths(item)


def check():
    errors = check_links(source_files(), ROOT)
    errors += docs_diagrams.check(DOCS / 'assets/diagrams')
    expected = compatibility()
    path = DOCS / 'reference/compatibility.md'
    if not path.exists() or path.read_text() != expected:
        errors.append('Compatibility reference is stale: run python tools/docs.py inventory')
    nav = list(nav_paths(json.loads((DOCS / 'navigation.json').read_text())))
    if len(nav) != len(set(nav)): errors.append('Navigation contains duplicate pages')
    for value in nav:
        if not (DOCS / value).is_file(): errors.append(f'Navigation target missing: {value}')
    for section in ['get-started', 'installation', 'user-guide', 'administration', 'concepts', 'reference', 'development']:
        for page in (DOCS / section).rglob('*.md'):
            key = page.relative_to(DOCS).as_posix()
            migration = json.loads((DOCS / 'migration.json').read_text())
            if key in migration and migration[key]['target'] != key: continue
            if key not in nav: errors.append(f'Canonical page is not navigable: {key}')
    for old, record in json.loads((DOCS / 'migration.json').read_text()).items():
        source = DOCS / old
        if not source.exists():
            errors.append(f'Legacy Markdown path missing: {old}')
            continue
        old_ids = parse(source).ids
        for anchor, destination in record['anchors'].items():
            if anchor not in old_ids: errors.append(f'Legacy anchor lost: {old}#{anchor}')
            target, _, fragment = destination.partition('#')
            p = DOCS / target
            if not p.exists(): errors.append(f'Migration target missing: {destination}')
            elif fragment and fragment not in parse(p).ids:
                errors.append(f'Migration target anchor missing: {destination}')
    if errors:
        print('\n'.join(sorted(set(errors))))
        return False
    print(f'Documentation checks passed: {len(nav)} navigation entries; source links, legacy anchors and catalog reference.')
    return True


def page_url(path):
    p = Path(path)
    return ('handbook/' + (p.parent.as_posix() + '/' if p.parent.as_posix() != '.' else '')) if p.name in ('README.md', 'index.md') else 'handbook/' + p.with_suffix('').as_posix() + '/'


def redirect_document(default, anchors):
    # All targets come from the checked local migration map, never request input.
    payload = json.dumps({'default':default, 'anchors':anchors}).replace('<', '\\u003c')
    return ('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width">'
            '<title>Documentation moved · Magic Stick</title><p>This page has moved. '
            f'<a href="{html.escape(default, quote=True)}">Open the current guide</a>.</p>'
            '<script>const routes=' + payload + ';let key=location.hash.slice(1);'
            'try{key=decodeURIComponent(key)}catch{}location.replace(routes.anchors[key]||routes.default);</script></html>')


def marketing_links(text):
    """Resolve canonical Markdown links in the landing page at build time."""
    def replace(match):
        href = match[2]
        url = urlsplit(href)
        if url.scheme or url.netloc or not url.path.endswith('.md'):
            return match[0]
        route = page_url(url.path)
        return match[1] + route + ('#' + url.fragment if url.fragment else '') + match[3]
    return re.sub(r'(href=")([^"]+)(")', replace, text)


def check_migration_output():
    errors, cache = [], {}
    for old, record in json.loads((DOCS / 'migration.json').read_text()).items():
        for route in [record['target'], *record['anchors'].values()]:
            path, _, fragment = route.partition('#')
            target = OUT / page_url(path) / 'index.html'
            if not target.is_file():
                errors.append(f'Legacy route {old}: missing rendered target {route}')
            elif fragment:
                if target not in cache: cache[target] = parse(target).ids
                if fragment not in cache[target]:
                    errors.append(f'Legacy route {old}: missing rendered anchor {route}')
    return sorted(set(errors))


def build():
    if not check(): return False
    if OUT.exists(): shutil.rmtree(OUT)
    OUT.mkdir(parents=True, exist_ok=True)
    subprocess.run([sys.executable, '-m', 'mkdocs', 'build', '--strict'], cwd=ROOT, check=True)
    for name in (*MARKETING_PAGES, 'site.css', 'site.js'):
        if name.endswith('.html'):
            (OUT / name).write_text(marketing_links((DOCS / name).read_text()))
        else:
            shutil.copy2(DOCS / name, OUT / name)
    for name in ('assets', 'sales-deck'):
        shutil.copytree(DOCS / name, OUT / name, dirs_exist_ok=True)
    subprocess.run([sys.executable, str(ROOT / 'tools/collect_python_notices.py'),
                    '--output', str(OUT / 'licenses/documentation-build.txt'),
                    'mkdocs', 'mkdocs-material'], cwd=ROOT, check=True)
    for old, record in json.loads((DOCS / 'migration.json').read_text()).items():
        rel = Path(old)
        # Legacy Jekyll/Pages addresses, as well as original raw Markdown links.
        aliases = [rel.with_suffix('.html')]
        if rel.name == 'README.md': aliases += [rel.parent / 'index.html']
        for alias in aliases:
            if alias.as_posix() == 'index.html': continue
            target = OUT / alias
            target.parent.mkdir(parents=True, exist_ok=True)
            def url(mapped):
                p, _, fragment = mapped.partition('#')
                route = page_url(p)
                relative = os.path.relpath(OUT / route, target.parent).replace(os.sep, '/') + '/'
                return relative + ('#' + fragment if fragment else '')
            target.write_text(redirect_document(url(record['target']), {k:url(v) for k,v in record['anchors'].items()}))
        md = OUT / old
        md.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(DOCS / old, md)
    (OUT / '.nojekyll').touch()
    site_url = yaml.safe_load((ROOT / 'mkdocs.yml').read_text())['site_url']
    prefix = urlsplit(site_url).path.rstrip('/').rsplit('/', 1)[0]
    errors = check_links(sorted(OUT.rglob('*.html')), OUT, prefix) + check_migration_output()
    if errors:
        print('\n'.join(errors))
        return False
    print(f'Static site built and checked: {OUT}')
    return True


def public_url(url):
    """Ignore local/private literal addresses and documentation placeholders."""
    parsed = urlsplit(url)
    host = parsed.hostname or ''
    if parsed.scheme not in ('http', 'https') or parsed.username or parsed.password or not host:
        return False
    if '<' in url or '{' in url or host == 'localhost' or host.endswith(('.local', '.localhost', '.internal')):
        return False
    if host in ('example.com', 'example.org', 'example.net') or any(host.endswith('.' + h) for h in ('example.com', 'example.org', 'example.net')):
        return False
    try:
        return ipaddress.ip_address(host).is_global
    except ValueError:
        return '.' in host


def external():
    urls = sorted({u.split('#')[0] for p in source_files() for u in parse(p).links if u.startswith(('https://', 'http://'))})
    # Public, literal URLs only. Never contact local hosts or placeholder destinations.
    urls = [u for u in urls if public_url(u)]
    def probe(url):
        try:
            req = Request(url, headers={'User-Agent':'MagicStick-docs-link-check/1.0'}, method='HEAD')
            with urlopen(req, timeout=10) as response: return {'url':url, 'status':response.status}
        except Exception as exc: return {'url':url, 'warning':str(exc)}
    with ThreadPoolExecutor(max_workers=8) as pool: results = list(pool.map(probe, urls))
    report = ROOT / 'dist/docs-external-links.json'
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(json.dumps(results, indent=2) + '\n')
    print(f'Advisory external links: {sum("warning" in r for r in results)} warnings / {len(results)} URLs. {report}')
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=('check', 'build', 'inventory', 'external'))
    args = parser.parse_args()
    if args.command == 'inventory':
        (DOCS / 'reference/compatibility.md').write_text(compatibility())
        return 0
    return 0 if {'check':check, 'build':build, 'external':external}[args.command]() else 1


if __name__ == '__main__':
    raise SystemExit(main())
