apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: ai
data:
  10-qwen359b.yaml: |
    - model_name: qwen359b
      litellm_params:
        model: openai/qwen359b
        api_base: http://qwen359b.ai.svc.cluster.local:8000/v1
        api_key: "none"
